apiVersion: v1
kind: Secret
metadata:
  name: duckdb-s3-credentials
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: replace-me
  AWS_SECRET_ACCESS_KEY: replace-me
  AWS_REGION: eu-central-1
  AWS_ENDPOINT_URL: s3.eu-central-1.amazonaws.com
  AWS_SESSION_TOKEN: ""
  S3_USE_SSL: "true"
  S3_URL_STYLE: vhost
  DBT_INPUT_URI_TEMPLATE: s3://my-bucket/raw/mandant={mandant}/stichtag=*/**/*.parquet
  DBT_OUTPUT_URI_TEMPLATE: s3://my-bucket/curated/mandant={mandant}/report_{run_id}.parquet

